// <auto-generated />
namespace Project.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productentityupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productentityupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201903021617437_product-entity-updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
