// <auto-generated />
namespace Project.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class journaltableslicechangerd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(journaltableslicechangerd));
        
        string IMigrationMetadata.Id
        {
            get { return "202011240807258_journal-table-slice-changerd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
