// <auto-generated />
namespace Project.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class journalandjournaltypeaddedandcompanytablemodified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(journalandjournaltypeaddedandcompanytablemodified));
        
        string IMigrationMetadata.Id
        {
            get { return "202011211304035_journal and journal type added and company table modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
