//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayslipDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Id { get; set; }
        public int Identity { get; set; }
        public string EpbPaymentReceiptNumber { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string ExporterId { get; set; }
        public System.DateTime DepositDate { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string TransectionNumber { get; set; }
        public string DepositorName { get; set; }
        public string DepositorAddress { get; set; }
        public string DepositorPhone { get; set; }
        public double TotalAmount { get; set; }
        public string AmountInWords { get; set; }
        public string BankDepositSlip { get; set; }
        public int TransectionStatus { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public int PaymentMethod { get; set; }
    
        public virtual Exporter Exporter { get; set; }
    }
}
