//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayslipDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpbService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EpbService()
        {
            this.EpbServiceLogs = new HashSet<EpbServiceLog>();
            this.ExporterEpbServices = new HashSet<ExporterEpbService>();
            this.ExporterEpbServicePrintLogs = new HashSet<ExporterEpbServicePrintLog>();
        }
    
        public string Id { get; set; }
        public int Identity { get; set; }
        public string PayslipRequestId { get; set; }
        public string ExporterId { get; set; }
        public string ExporterNumber { get; set; }
        public string ExporterName { get; set; }
        public System.DateTime ServiceRequestedDate { get; set; }
        public System.DateTime ServiceApprovedDate { get; set; }
        public System.DateTime ServiceRejectedDate { get; set; }
        public int TotalServiceQuantity { get; set; }
        public double TotalServiceAmount { get; set; }
        public int ServiceStatus { get; set; }
        public double InitialCurrentBalance { get; set; }
        public double AfterServiceTakenBalance { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public int PrintCount { get; set; }
    
        public virtual Exporter Exporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpbServiceLog> EpbServiceLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExporterEpbService> ExporterEpbServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExporterEpbServicePrintLog> ExporterEpbServicePrintLogs { get; set; }
    }
}
