//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayslipDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpbServiceLog
    {
        public string Id { get; set; }
        public string EpbServiceId { get; set; }
        public string PayslipRequestId { get; set; }
        public string UserId { get; set; }
        public string Username { get; set; }
        public string UserFullName { get; set; }
        public int ServiceStatus { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual EpbService EpbService { get; set; }
    }
}
