//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayslipDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exporter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exporter()
        {
            this.Accounts = new HashSet<Account>();
            this.EpbServices = new HashSet<EpbService>();
            this.ExporterEpbServices = new HashSet<ExporterEpbService>();
        }
    
        public string Id { get; set; }
        public int ExporterCategory { get; set; }
        public string ExporterType { get; set; }
        public string ExporterNumber { get; set; }
        public int IdentityId { get; set; }
        public string EpbRegistrationNo { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime RegistrationValidSince { get; set; }
        public System.DateTime PeriodofValidation { get; set; }
        public bool IsUndertakingByExporter { get; set; }
        public int ActiveState { get; set; }
        public string CompanyOrFactoryName { get; set; }
        public string CorporateAddress { get; set; }
        public string CorporateAddressPost { get; set; }
        public string CorporateAddressDistrict { get; set; }
        public string CorporateAddressCountry { get; set; }
        public string FactoryType { get; set; }
        public string FactoryAddress { get; set; }
        public string FactoryAddressPost { get; set; }
        public string FactoryAddressDistrict { get; set; }
        public string FactoryAddressCountry { get; set; }
        public string AssociationMembershipNo { get; set; }
        public string AssociationBinNo { get; set; }
        public string AssociationTradeLicense { get; set; }
        public string AssociationTinNo { get; set; }
        public string ActivityDescription { get; set; }
        public string IndustrialProcessDescription { get; set; }
        public string GoodsDescription { get; set; }
        public string HsCode { get; set; }
        public string Bonded { get; set; }
        public string ErcNo { get; set; }
        public string BolRegNo { get; set; }
        public string FireLicNo { get; set; }
        public string BondLicNo { get; set; }
        public int ServiceOffice { get; set; }
        public int EpbReferenceNo { get; set; }
        public double TotalDepositedAmount { get; set; }
        public double TotalServiceTakenAmount { get; set; }
        public double CurrentBalance { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public string PrimaryPersonName { get; set; }
        public string PrimaryPersonPhone { get; set; }
        public string PrimaryPersonAddress { get; set; }
        public string SecondaryPersonName { get; set; }
        public string SecondaryPersonPhone { get; set; }
        public string SecondaryPersonAddress { get; set; }
        public string CommercialManagerName { get; set; }
        public string CommercialManagerPhone { get; set; }
        public string CommercialManagerAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpbService> EpbServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExporterEpbService> ExporterEpbServices { get; set; }
    }
}
