//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayslipDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExporterEpbService
    {
        public string Id { get; set; }
        public string EpbServiceId { get; set; }
        public string ExporterId { get; set; }
        public string ServiceTypeId { get; set; }
        public string ServiceIssueTypeId { get; set; }
        public int Quantity { get; set; }
        public int ServiceHour { get; set; }
        public double ServiceAmount { get; set; }
        public string SubitemOf { get; set; }
        public int Identity { get; set; }
        public string PayslipNumber { get; set; }
        public string BarcodeNumber { get; set; }
        public int PrintCount { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public string BarcodeImageUrl { get; set; }
        public string BarcodeFileName { get; set; }
    
        public virtual EpbService EpbService { get; set; }
        public virtual Exporter Exporter { get; set; }
        public virtual ServiceIssueType ServiceIssueType { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
