//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayslipDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public string Id { get; set; }
        public string TransectionId { get; set; }
        public System.DateTime TransectionDate { get; set; }
        public string TransectionParticular { get; set; }
        public double Withdraw { get; set; }
        public double Deposit { get; set; }
        public double Balance { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    }
}
