//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GspDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Distributor()
        {
            this.DistributorUserProfiles = new HashSet<DistributorUserProfile>();
            this.FormAs = new HashSet<FormA>();
            this.FormAAssigns = new HashSet<FormAAssign>();
            this.FormAIssues = new HashSet<FormAIssue>();
        }
    
        public System.Guid Id { get; set; }
        public string DistributorNo { get; set; }
        public string Name { get; set; }
        public string Organization { get; set; }
        public int ActiveStateId { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> PsId { get; set; }
        public Nullable<System.Guid> PrimaryPersonId { get; set; }
        public Nullable<System.Guid> SecondaryPersonId { get; set; }
        public int IdentityId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<System.Guid> ChangedBy { get; set; }
    
        public virtual ActiveState ActiveState { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Thana Thana { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributorUserProfile> DistributorUserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormA> FormAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormAAssign> FormAAssigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormAIssue> FormAIssues { get; set; }
    }
}
