//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GspDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormALog
    {
        public System.Guid Id { get; set; }
        public System.Guid FromAId { get; set; }
        public int FormAStateId { get; set; }
        public string Descripton { get; set; }
        public System.DateTime ActionDate { get; set; }
        public System.Guid ActionBy { get; set; }
    
        public virtual FormA FormA { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual FormAState FormAState { get; set; }
    }
}
