//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GspDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormADocument
    {
        public System.Guid FormAId { get; set; }
        public System.Guid DocumentId { get; set; }
        public int FormADocumentTypeId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public Nullable<System.Guid> ChangedBy { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual FormA FormA { get; set; }
        public virtual FormADocumentType FormADocumentType { get; set; }
    }
}
