//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GspDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormACategory
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FormAId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ProductCodeId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual FormA FormA { get; set; }
        public virtual ProductCode ProductCode { get; set; }
    }
}
