//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GspDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormAAssign
    {
        public System.Guid Id { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid DistributorId { get; set; }
        public string FormAFrom { get; set; }
        public string FormATo { get; set; }
        public int Total { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
