//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GspDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GspDBEntities : DbContext
    {
        public GspDBEntities()
            : base("name=GspDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveState> ActiveStates { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Culture> Cultures { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<DistributorUserProfile> DistributorUserProfiles { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Exporter> Exporters { get; set; }
        public virtual DbSet<FactoryType> FactoryTypes { get; set; }
        public virtual DbSet<FormA> FormAs { get; set; }
        public virtual DbSet<FormAAssign> FormAAssigns { get; set; }
        public virtual DbSet<FormACategory> FormACategories { get; set; }
        public virtual DbSet<FormADocument> FormADocuments { get; set; }
        public virtual DbSet<FormADocumentType> FormADocumentTypes { get; set; }
        public virtual DbSet<FormAIssue> FormAIssues { get; set; }
        public virtual DbSet<FormALog> FormALogs { get; set; }
        public virtual DbSet<FormAState> FormAStates { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<ProductCode> ProductCodes { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceDetail> ResourceDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thana> Thanas { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
