//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GspDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceDetail
    {
        public string ResourceKey { get; set; }
        public string Culture { get; set; }
        public string ResourceValue { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Culture Culture1 { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
